<?php
$_helper = $this->helper('MageGuide\Skroutz\Helper\Data');
$isActive = $_helper->getIsActive();
$programID = $_helper->getProgramID();

if ($isActive && $programID != "") :
?>

    <!-- SKROUTZ ANALYTICS CODE start -->
    <script>
        skroutz_analytics('ecommerce', 'addOrder', 
            <?= sprintf("{
                order_id: '%s',
                revenue: '%.2f',
                shipping: '%.2f',    // Total Shipping Cost. Does not include payment costs.
                tax: '%.2f'
            }", 
                $block->getRealOrderId(),   // Order ID. Required.
                $block->getPrice(),         // Grand Total. Includes Tax and Shipping. Does not include payment costs.
                $block->getShippingCost(),  // Total Shipping Cost. Does not include payment costs.
                $block->getTaxAmount()      // Total Tax.
            ); ?>
        );
    </script>

    <?php 
        $items = $block->getAllOrderVisibleItems();
        $itemDiscounts = $block->distributeCartDiscounts($items);
    ?>

    <script>
        <?php 
        foreach ($items as $index => $item) {
            $child_id = $block->getChildId($item->getSku());
            $parent_id = $block->getParentId($child_id);

            if ($parent_id) {
                $item_sku = $block->getSkuFromId($parent_id);
            } else {
                $item_sku = $block->getSkuFromId($child_id);
            }
        ?>

            skroutz_analytics('ecommerce', 'addItem',
                <?= sprintf("{
                    order_id: '%s',
                    product_id: '%s',
                    name: '%s',
                    price: '%.2f',
                    quantity: '%d'
                }",
                    $block->getRealOrderId(),            // Order ID. Required.
                    $block->escapeJs($item_sku),        // Product ID. Required.
                    $block->escapeJs($item->getName()), // Product Name. Required.
                    $item->getPriceInclTax() +
                            $itemDiscounts[$index],         // Price per Unit. Required.
                    $item->getQtyOrdered()              // Quantity of Items. Required.
                ); ?>
            );

        <?php } ?>
    </script>
    <!-- SKROUTZ ANALYTICS CODE end -->

<?php endif; ?>